### ISSUE TITLE
Y error 

### ISSUE THREAD

**Issue by othomantegazza** [estraven-collective/snow-and-ice#1]
The y axis is shifted about 18km.

<img width="520" alt="Screenshot 2023-03-14 at 12 07 35" src="https://user-images.githubusercontent.com/7520072/224982934-dfab87ff-7afb-4591-aed9-4348bd03a106.png">

Investigate if it's an issue with how we read the VIIRS satellite data, or with the overlaid border data from `rnaturalearthdata`.

**Comment by giorgia-dit** [comment]
Resolution attempts:
- checked if projection mismatch  >  no;
- checked if approximation error (in VIIRS reading)  >  no;
- global check of reading VIIRS data script, compared with details in the guide  >  no potential issues found;
- used another .shp file for Italy, different from the one given by `rnaturalearthdata`  >  result doesn't change.

**Comment by othomantegazza** [comment]
Sorry, I was exploring a bit the data and while plotting, the shift caught my eye again, and it is definitely problem with the raster satellite data, emerging probably in the code that I've put together to parse them and to add projection metadata.

<img width="1112" alt="Screenshot 2023-04-13 at 20 44 50" src="https://user-images.githubusercontent.com/7520072/231854016-a37947ef-27ba-40b8-9b56-65d3eebe31a7.png">

The longitude of the raster is definitely out of place, considering that when we fetch the data from the API, we arbitrarily query for a bounding box of:

```r
    W = 5,
    S = 43,
    E = 13,
    N = 48,
```
The W and N are the longitude and latitude of the top left corner. The longitude seems fine, while the latitude seems definitely off. Same thing for E and S, which refer to the bottom right corner.

**Comment by othomantegazza** [comment]
Or actually, the bounding box might be bottom_left, top_right, in that case also the longitude is out?

(See the parameter "bounding_box" at https://nsidc.org/data/user-resources/help-center/table-key-value-pair-kvp-operands-subsetting-reformatting-and-reprojection-services)

**Comment by othomantegazza** [comment]
I was also checking the output of `st_crs()` on the star object that we read, there's a lot more metadata other than the proj4 string.

Maybe some of this could hold the key to get the right position.

```
Coordinate Reference System:
  User input: +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs 
  wkt:
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["unknown",
        METHOD["Sinusoidal"],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```

**Comment by othomantegazza** [comment]
But a quick solution that we could test....

When we query NASA APIs to get the data, we could ask them to [convert the format to a new one](https://nsidc.org/data/user-resources/help-center/table-key-value-pair-kvp-operands-subsetting-reformatting-and-reprojection-services):

```
[GeoTIFF, HDF-EOS5, NetCDF4-CF, NetCDF-3, ASCII, TABULAR_ASCII, HDF-EOS, KML, Shapefile] 
```
Right now we are using HDF-EOS5, which is default for VIIRS data, but maybe with other formats, such as GeoTIFF, are easier to upload in R. Not sure if this is worth a try.

**Comment by othomantegazza** [comment]
Giorgia, I tried to download the file in GeoTIFF format, and it might be that it works just out of the box. 🤦 

I read them with:

```r
stars::read_stars('path/to/file.tif')
```

Without doing any extra operation on metadata. This is what I get when I plot it:

<img width="730" alt="Screenshot 2023-04-15 at 16 51 32" src="https://user-images.githubusercontent.com/7520072/232232112-49e936a5-78bb-4a8a-addc-9ff3baad3780.png">
